import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        tablet: "768px",
        desktop: "1024px",
      },
      fontFamily: {
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
        display: ["var(--font-headline)", "system-ui", "sans-serif"],
        headline: ["var(--font-headline)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        label: ["var(--font-body)", "system-ui", "sans-serif"],
        mono: ["SFMono-Regular", "monospace"],
      },
      colors: {
        brand: {
          primary: "#4f46e5",
          secondary: "#0f172a",
          accent: "#22d3ee",
        },
        "on-secondary-fixed": "#001a41",
        "primary-fixed": "#9eefff",
        "on-primary": "#00363e",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary-fixed-dim": "#89ceff",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#006876",
        secondary: "#adc6ff",
        "surface-container-lowest": "#080e18",
        "on-surface": "#dde2f1",
        "inverse-surface": "#dde2f1",
        "on-background": "#dde2f1",
        "tertiary-fixed": "#c8e6ff",
        error: "#ffb4ab",
        "on-secondary-container": "#e0e8ff",
        "surface-variant": "#2f3540",
        "inverse-on-surface": "#2b313c",
        outline: "#859396",
        "on-primary-fixed-variant": "#004e59",
        "on-tertiary-fixed-variant": "#004c6e",
        tertiary: "#b9e0ff",
        "on-tertiary-container": "#005378",
        "surface-tint": "#29d9f2",
        "surface-bright": "#333945",
        "on-surface-variant": "#bbc9cc",
        "secondary-fixed": "#d8e2ff",
        "secondary-container": "#0064d4",
        "surface-container-highest": "#2f3540",
        "surface-container": "#1a202a",
        "on-secondary-fixed-variant": "#004494",
        "on-tertiary": "#00344d",
        "on-tertiary-fixed": "#001e2f",
        "surface-container-high": "#242a35",
        surface: "#0e141d",
        "on-error": "#690005",
        "surface-container-low": "#161c26",
        primary: "#7cebff",
        "on-primary-container": "#005661",
        "outline-variant": "#3c494c",
        "surface-dim": "#0e141d",
        background: "#0e141d",
        "tertiary-container": "#76c8ff",
        "primary-fixed-dim": "#29d9f2",
        "primary-container": "#13d2eb",
        "on-secondary": "#002e69",
        "error-container": "#93000a",
        "on-primary-fixed": "#001f24",
      },
    },
  },
  plugins: [],
};

export default config;
